name: Run

on:
  workflow_dispatch: {}

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/use-kubelogin@45e09682adb5a0cad41a04ddd56a806dfeb79b4a
      with:
        kubelogin-version: 'latest'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - run: |
        kubelogin --version
